
spring:
  application:
    name: meeapp-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/meeapp
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:dandelionkwamebentum1@gmail.com}
    password: ${MAIL_PASSWORD:yjzxlsbzsszxhhwm}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.meeapp: DEBUG
    org.springframework.security: DEBUG

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey}
    expiration: 86400000 # 24 hours
  
#  cors:
#    allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:8081}